# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster_random"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Remove forward-char widgets from ACCEPT
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=("${(@)ZSH_AUTOSUGGEST_ACCEPT_WIDGETS:#forward-char}")
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=("${(@)ZSH_AUTOSUGGEST_ACCEPT_WIDGETS:#vi-forward-char}")

# Add forward-char widgets to PARTIAL_ACCEPT
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(forward-char)
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=(vi-forward-char)

plugins=(
    git
    jump
    zsh-autosuggestions
    zsh-history-substring-search
    zsh-syntax-highlighting # must be the last plugin sourced
)

source $ZSH/oh-my-zsh.sh

bindkey "^[h" backward-char                 # Alt+h
bindkey "^[j" down-line-or-search           # Alt+j
bindkey "^[k" up-line-or-search             # Alt+k
bindkey "^[l" forward-char                  # Alt+l
bindkey "^[." autosuggest-accept            # Alt+.
bindkey "^J"  autosuggest-execute           # Ctrl+J
bindkey "^[]" history-substring-search-down # Alt+]
bindkey "^[[" history-substring-search-up   # Alt+[

[[ $TMUX = "" ]] && export TERM="xterm-256color"

# man page color
export LESS_TERMCAP_mb=$'\E[1;31m'
export LESS_TERMCAP_md=$'\E[38;5;37;1m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_so=$'\E[38;5;24;48;5;148;1m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_us=$'\E[38;5;11;1m'
export LESS_TERMCAP_ue=$'\E[0m'

# zsh history config
export HISTSIZE=1024
export HISTFILESIZE=1024
export HISTFILE=$HOME/.zsh_history
export SAVEHIST=$HISTSIZE
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt hist_ignore_all_dups

if [ -e $HOME/.ls_colors ]; then
    eval $( dircolors -b $HOME/.ls_colors )
fi

alias j="jump"

setopt rmstarsilent
setopt no_nomatch

# remove duplicate PATH entries
# this line comes after export PATH=XXXXXX
# PATH=$(printf %s "$PATH" | awk -vRS=: '!a[$0]++' | paste -s -d:)

